if (CMAKE_SYSTEM_NAME MATCHES "Linux")
	set(Caffe_DIR 3rdparty/caffe_build)
	message(STATUS "Caffe_DIR is ${Caffe_DIR}")
	find_package(Caffe)
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
	option(WithCaffe "Caffe Model" OFF)
	if(WithCaffe MATCHES ON)
		find_path(Caffe_DIR "3rdparty/caffe")
	endif(WithCaffe MATCHES ON)
endif ()
