set(RC_GUI_FILES ${PROJECT_SOURCE_DIR}/src/rc_gui/rcGUI.cpp)

if (RC_LIB STREQUAL "OFF")
    set(LIB_NAME rcgui)
    add_library(${LIB_NAME} SHARED ${RC_GUI_FILES})
    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        target_link_libraries(${LIB_NAME} ${OPENCV_LIBS})
    elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
        set(SLIB_NAME lrcgui)
        add_library(${SLIB_NAME} ${RC_GUI_FILES})
        target_link_libraries(${LIB_NAME} ${OpenCV_LIB})
    endif ()
endif ()
