set(RC_LOG_FILES ${PROJECT_SOURCE_DIR}/src/rc_log/rclog.cpp)
include_directories(src/include)
if (RC_LIB STREQUAL "OFF")
    set(LIB_NAME rclog)
    add_library(${LIB_NAME} SHARED ${RC_LOG_FILES})
    if (CMAKE_SYSTEM_NAME MATCHES "Windows")
        set(SLIB_NAME lrclog)
        add_library(${SLIB_NAME} ${RC_LOG_FILES})
    endif ()
endif ()