set(LIB_NAME rclog)
set(SOURCE_FILES src/rc_log/rclog.cpp)
include_directories(src/include)
add_library(${LIB_NAME} SHARED ${SOURCE_FILES})
if(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(SLIB_NAME lrclog)
    add_library(${SLIB_NAME} ${SOURCE_FILES})
endif ()