set(EXE_NAME RoboCar)
set(SOURCE_FILES ${PROJECT_SOURCE_DIR}/src/rc_main/main.cpp)

add_executable(${EXE_NAME} ${SOURCE_FILES})
if (RC_LIB STREQUAL "OFF")
    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        target_link_libraries(${EXE_NAME} ${OpenCV_LIBS} rctask rclog rcmove rccv)
    elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
        target_link_libraries(${EXE_NAME} ${OPENCV_LIB} lrctask lrclog lrccv lrcmove)
    endif ()
else ()
    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        target_link_libraries(${EXE_NAME} ${OpenCV_LIBS} rc pthread)
    elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
        target_link_libraries(${EXE_NAME} ${OPENCV_LIB} lrc)
    endif ()
endif ()
