if (CMAKE_SYSTEM_NAME MATCHES "linux")
	set(OpenCV_DIR 3rdparty/opencv_build)
	message(STATUS "opencv_dir is ${OpenCV_DIR}")
	find_package(OpenCV required)
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
	find_path(OpenCV_DIR NAMES OpenCVConfig.cmake PATHS ${PROJECT_SOURCE_DIR}/3rdparty/opencv DOC "OpenCV Path")
	include_directories(${OpenCV_DIR}/include)
	message(${OpenCV_DIR})
	find_library(OPENCV_LIB opencv_world320 ${OpenCV_DIR}/x64/vc14/lib)
	link_directories(${OpenCV_DIR}/x64/vc14/lib)
endif (CMAKE_SYSTEM_NAME MATCHES "linux")