if (RC_TEST)
include_directories(src/include)

set(SERIAL_TEST ${PROJECT_SOURCE_DIR}/src/rc_test/rc_serial_test.cpp)
add_executable(rc_serial_test ${SERIAL_TEST})
target_link_libraries(rc_serial_test rcserial rclog)

set(CV_TEST ${PROJECT_SOURCE_DIR}/src/rc_test/rc_cv_test.cpp)
add_executable(rc_cv_test ${CV_TEST})
target_link_libraries(rc_cv_test ${OpenCV_LIBS} rccv rclog)

link_directories(${PROJECT_SOURCE_DIR}/3rdparty)
set(RADAR_TEST ${PROJECT_SOURCE_DIR}/src/rc_test/rc_radar_test.cpp)
add_executable(rc_radar_test ${RADAR_TEST})
target_link_libraries(rc_radar_test ${OpenCV_LIBS} rcmapping rclog pthread)
#target_link_libraries(rc_cv_test ${OpenCV_LIBS} rccv rclog)
#set(VLC_TEST src/rc_test/rc_vlc_test.cpp)
#add_executable(rc_vlc_test ${VLC_TEST})
#target_link_libraries(rc_vlc_test ${OpenCV_LIBS}  rccv rclog)
endif ()
