if (RC_TEST)
set(SERIAL_TEST src/rc_test/rc_serial_test.cpp)
set(CV_TEST src/rc_test/rc_cv_test.cpp)
include_directories(src/include)
add_executable(rc_serial_test ${SERIAL_TEST})
add_executable(rc_cv_test ${CV_TEST})
target_link_libraries(rc_serial_test rcserial rclog)
target_link_libraries(rc_cv_test rcserial rclog)
endif ()
